[tool.ruff]
line-length = 120  # defaults to 88 like black
target-version = "py39"  # the python version to target, useful when considering code upgrades, defaults to "py310"

select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade,
  "I",   # isort
]

[tool.ruff.per-file-ignores]
"samples/basic_service/basic_service.py" = ["F821"]
