[tool.poetry]
name = "sakura"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aio-pika = "9.0.4"
fastapi = "0.78.0"
loguru = "^0.7.0"
uvicorn = "^0.23.1"
uvloop = { version = "^0.17.0", optional = true }
dynaconf = "^3.2.0"
asyncer = "^0.0.2"

[tool.poetry.extras]
uvloop = ["uvloop"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
