config:
  queue:
    name: hello
  exchange:
    name: main

transporters: {}

providers:
  http:
    type: FastAPIProvider
    params:
      port: 8000
      title: basic_service

loggers:
  Loguru:
    serialize: False
    handlers: []
