config:
  queue:
    name: hello
  exchange:
    name: main

transporters:
  PubSubTransporter:
    clients:
      first_client:
        type: RabbitMQClient
        params:
          uri: amqp://guest:guest@localhost

providers:
  http:
    type: FastAPIProvider
    params:
      port: 8000
      title: basic_service

loggers:
  Loguru:
    serialize: False
    handlers: []
