config:
  queue:
    name: hello
  exchange:
    name: main

transporters:
  HTTPTransporter:
    client:
      type: FastAPI
      params:
        port: 8000
        title: basic_service

  PubSubTransporter:
    clients:
      first_client:
        type: RabbitMQClient
        params:
          uri: amqp://guest:guest@localhost

providers: {}

loggers:
  Loguru:
    serialize: False
    handlers: []
