transporters:
  HTTPTransporter:
    client:
      type: FastAPI
      params:
        port: 8000
        title: basic_service

providers: {}
config: {}

loggers:
  Loguru:
    serialize: False
    handlers: []
