name: CI for fastapi package
on:
  push:
    paths:
      - sakura/providers/fastapi/**
      - .github/workflows/fastapi/**
    branches:
      - configuring-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
