name: CI for sakura-fastapi-provider

on:
  push:
    paths:
      - sakura/providers/fastapi_provider/**
      - .github/workflows/fastapi_provider_ci.yaml
    branches:
      - configuring-ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -

    - name: Install project dependencies with Poetry
      run: poetry install --no-dev --no-root --extras fastapi

    - name: Install build dependencies
      run: pip install setuptools wheel twine

    - name: Build package
      run: poetry build

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: sakura-fastapi-provider
        path: dist/sakura-fastapi-provider-0.1.0.tar.gz

#    - name: Publish to PyPI
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
#      run: twine upload dist/*
