name: Publish workflow for sakura-core

on:
  push:
    paths:
      - sakura/**
      - .github/workflows/sakura_core_publish.yaml
    branches:
      - configuring-ci

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -

    - name: Install project dependencies with Poetry
      run: poetry install --no-dev --no-root

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.17
      with:
        python_version: "3.10.9"
        poetry_version: "==1.5.1"
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        package_directory: "sakura"
